import type { Metadata } from "next";
import { Advent_Pro, Inter } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers/providers";
import CustomFooter from "../components/Footer/Footer";
import NavBar from "../components/ui/Navbar/Navbar";
import NavbarCustomContent from "../components/ui/Navbar/NavbarContent";
import BagModal from "../components/Bag/BagModal";
import BuyRightNowModal from "../components/Bag/BuyRightNowModal";
import SearchInput from "../components/ui/SearchInput/SearchInput";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cormorant = Advent_Pro({
  weight: ["400", "300", "500", "600", "700", "800"],
  subsets: ["latin", "cyrillic"],
  variable: "--defaultFont",
});
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <div
      className={`${inter.className} ${cormorant.className} ${cormorant.variable} `}
    >
      <NavBar />
      {children}
      {modal}
      <CustomFooter />
    </div>
  );
}
