import type { Metadata } from "next";
import { Advent_Pro, Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cormorant = Advent_Pro({
  weight: ["400", "300", "500", "600", "700", "800"],
  subsets: ["latin", "cyrillic"],
  variable: "--defaultFont",
});
export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  return (
    <div
      className={`${inter.className} ${cormorant.className} ${cormorant.variable} `}
    >
      {children}
    </div>
  );
}
