import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Cinzel } from "@next/font/google";
import { Providers } from "./providers/providers";
import CustomFooter from "./components/Footer/Footer";
import NavBar from "./components/ui/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--cinzel-font",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${cinzel.className} ${cinzel.variable} `}
      >
        <Providers>
          <NavBar />
          {children}
          <CustomFooter />
        </Providers>
      </body>
    </html>
  );
}
